// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlhxB3Ib4QBlCo2Gd7NQKRKqMrgnaLty0',
    appId: '1:1020252027861:web:34455eef880277affa5b5c',
    messagingSenderId: '1020252027861',
    projectId: 'fixit-19d80',
    authDomain: 'fixit-19d80.firebaseapp.com',
    storageBucket: 'fixit-19d80.appspot.com',
    measurementId: 'G-S5M682W23Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0oW9MDDbGnxisGL2FnKJP69ZhIpQE1OU',
    appId: '1:1020252027861:android:491810ba030ba0b6fa5b5c',
    messagingSenderId: '1020252027861',
    projectId: 'fixit-19d80',
    storageBucket: 'fixit-19d80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Rq-onuiLtMbhaVQYndTikOLvLR4D3wk',
    appId: '1:1020252027861:ios:cebb7f7ee09d1702fa5b5c',
    messagingSenderId: '1020252027861',
    projectId: 'fixit-19d80',
    storageBucket: 'fixit-19d80.appspot.com',
    iosBundleId: 'com.example.fixit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Rq-onuiLtMbhaVQYndTikOLvLR4D3wk',
    appId: '1:1020252027861:ios:70004eef6bcf1eccfa5b5c',
    messagingSenderId: '1020252027861',
    projectId: 'fixit-19d80',
    storageBucket: 'fixit-19d80.appspot.com',
    iosBundleId: 'com.example.fixit.RunnerTests',
  );
}
